sigstore, test: add licenses, testing
Signed-off-by: William Woodruff <william@trailofbits.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,14 +33,13 @@ jobs:
     steps:
       # adapted from Warehouse's bin/licenses
       - run: |
-          for fn in $(find . -type f -name "*.py"); do
-              # Check for license in first 5 lines (allows for shebang,
-              # encoding and handles comment character in various languages)
-              if [[ ! "$(head -5 $fn | grep "^ *\(#\|\*\|\/\/\) .* License\(d*\)")" ]]; then
-                  echo $fn is missing a license
-                  exit 1
-              fi
-          done
+        for fn in $(find . -type f -name "*.py"); do
+          echo "license: ${fn}"
+          if [[ ! "$(head -5 $fn | grep "^ *\(#\|\*\|\/\/\) .* License\(d*\)")" ]]; then
+            echo "${fn} is missing a license"
+            exit 1
+          fi
+        done
   lint:
     runs-on: ubuntu-latest
     steps:
