fix timestamp tests
Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

diff --git a/.github/workflows/test-with-setup-sigstore-env.yml b/.github/workflows/test-with-setup-sigstore-env.yml
--- a/.github/workflows/test-with-setup-sigstore-env.yml
+++ b/.github/workflows/test-with-setup-sigstore-env.yml
@@ -31,9 +31,14 @@ jobs:
             cache-dependency-path: pyproject.toml
         - run: |
             export TEST_SETUP_SIGSTORE_ENV="any non-empty value"
-            export SIGSTORE_IDENTITY_TOKEN_local=$( cat ${{ steps.setup-sigstore-env.outputs.oidc-token }} )
             export TRUST_CONFIG=${{ steps.setup-sigstore-env.outputs.trust-config }}
+            export SIGSTORE_IDENTITY_TOKEN_local=$( cat ${{ steps.setup-sigstore-env.outputs.oidc-token }} )
+            export TEST_SIGSTORE_TIMESTAMP_AUTHORITY_URL="${{ steps.setup-sigstore-env.outputs.tsa-url }}/api/v1/timestamp"
 
             set -o pipefail
             make test TEST_ARGS=" -rs -vv --showlocals" | tee output
             ! grep -q "skipping test that use the local environment" output || (echo "ERROR: Found skip message" && exit 1)
+
+            make test TEST_ARGS="-m timestamp_authority -rs -vv --showlocals" | tee output
+            ! grep -q "skipping test that use the local environment" output || (echo "ERROR: Found skip message" && exit 1)
+            ! grep -q "skipping test that requires a Timestamp Authority" output || (echo "ERROR: Found skip message" && exit 1)
